Fix issue #12: usage of array method name (join, shift, unshift, ...) as topic part (#13)
* Fix Issue #10 - removeAllListener may fail with TypeError

TypeError: Cannot read property 'pattern' of undefined
was happening when all listeners on a topic was manually removed prior to call removeAllListeners.

* upgrade mqtt-store to 2.1.0

* add test to reproduce issue #11