Fix Issue #10 - removeAllListener may fail with TypeError
TypeError: Cannot read property 'pattern' of undefined
was happening when all listeners on a topic was manually removed prior to call removeAllListeners.